# Generated by Django 4.1.1 on 2022-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="max_team_size",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="event",
            name="min_team_size",
            field=models.IntegerField(default=1),
        ),
    ]
