# Generated by Django 4.1.1 on 2022-10-26 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_max_team_size_alter_event_min_team_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("type", models.TextField()),
                ("image_url", models.URLField()),
            ],
        ),
    ]
