# Generated by Django 4.1.1 on 2022-11-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_latitude_event_longitude_event_subtype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="join_url",
        ),
    ]
