# Generated by Django 4.1.1 on 2022-11-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_team_join_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="subtype",
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("CULTURAL", "cultural event"),
                    ("TECHNICAL", "technical event"),
                    ("MEGASHOWS", "megashows event"),
                ],
                default="TECHNICAL",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("DANCE", "dance event"),
                    ("MUSIC", "music event"),
                    ("CODING", "coding event"),
                    ("HARDWARE", "hardware event"),
                ],
                default="DANCE",
                max_length=15,
            ),
        ),
    ]
