# Generated by Django 4.1.1 on 2022-11-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_event_subtype_event_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="rulebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("CULTURAL", "cultural event"),
                    ("TECHNICAL", "technical event"),
                    ("MEGASHOWS", "megashows event"),
                    ("WORKSHOPS", "workshops"),
                ],
                default="TECHNICAL",
                max_length=15,
            ),
        ),
    ]
