# Generated by Django 4.1.1 on 2022-11-05 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_rulebook_url_alter_event_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="datetime",
        ),
        migrations.RemoveField(
            model_name="event",
            name="duration",
        ),
        migrations.AddField(
            model_name="event",
            name="enddatetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 5, 16, 19, 46, 801811)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="startdatetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 5, 16, 19, 58, 323575)
            ),
            preserve_default=False,
        ),
    ]
