# Generated by Django 4.1.1 on 2022-11-10 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0007_club_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teammembers",
            unique_together={("team", "user")},
        ),
    ]
