# Generated by Django 4.1.1 on 2022-11-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_event_subcategory"),
        ("events", "0009_alter_event_subcategory"),
    ]

    operations = []
